### ISSUE TITLE
Exclude require statements inside strings

### ISSUE THREAD

**Issue by Aaronius** [yiminghe/match-require#2]
Thanks for the work done here. I would love to see the ability to exclude require statements that are inside strings as well. For example:

```
var x = "var clientInfo = require('client-info');"
```

It shouldn't match the `require` in the string.

This is an actual problem I'm running into. I'm writing a webpack loader which runs after a coverage loader like istanbul has instrumented the code. The instrumentation injects a bunch of strings containing code (like the above example) which messes up my loader because the loader ends up trying to replace the `require` statements in the string when it shouldn't.

**Comment by yiminghe** [comment]
I prefer not to do a full ast scan for efficiency , can you modify your code:

```js
var x = "var clientInfo = requ"+"ire('client-info');"
```
